config/routes.rb
Bg::Application.routes.draw do

  resources :merchant_children

  resources :merchant_pers

  resources :templates
  root to: "templates#index"
  resources :income
  resources :expence

  get 'public/data/:id' => 'templates#download', as: :download

end

app/controllers/merchant_children_controller.rb
class MerchantChildrenController < ApplicationController
  before_action :set_merchant_child, only: [:show, :edit, :update, :destroy]

  # GET /merchant_children
  # GET /merchant_children.json
  def index
    @merchant_children = MerchantChild.all
  end

  # GET /merchant_children/1
  # GET /merchant_children/1.json
  def show
  end

  # GET /merchant_children/new
  def new
    @merchant_child = MerchantChild.new
  end

  # GET /merchant_children/1/edit
  def edit
  end

  # POST /merchant_children
  # POST /merchant_children.json
  def create
    @merchant_child = MerchantChild.new(merchant_child_params)

    respond_to do |format|
      if @merchant_child.save
        format.html { redirect_to @merchant_child, notice: 'Merchant child was successfully created.' }
        format.json { render action: 'show', status: :created, location: @merchant_child }
      else
        format.html { render action: 'new' }
        format.json { render json: @merchant_child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchant_children/1
  # PATCH/PUT /merchant_children/1.json
  def update
    respond_to do |format|
      if @merchant_child.update(merchant_child_params)
        format.html { redirect_to @merchant_child, notice: 'Merchant child was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @merchant_child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchant_children/1
  # DELETE /merchant_children/1.json
  def destroy
    @merchant_child.destroy
    respond_to do |format|
      format.html { redirect_to merchant_children_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant_child
      @merchant_child = MerchantChild.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merchant_child_params
      params.require(:merchant_child).permit(:name, :merchant_per_id)
    end
end

app/helpers/merchant_children_helper.rb
module MerchantChildrenHelper
end

app/views/merchant_children/_form.html.haml
= form_for @merchant_child do |f|
  - if @merchant_child.errors.any?
    #error_explanation
      %h2= "#{pluralize(@merchant_child.errors.count, "error")} prohibited this merchant_child from being saved:"
      %ul
        - @merchant_child.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :name
    -#= f.text_field :merchant_per_id
    = f.collection_select :merchant_per_id,  MerchantPer.all, :id, :name
  .actions
    = f.submit 'Save'

app/views/merchant_children/edit.html.haml
%h1 Editing merchant_child

= render 'form'

= link_to 'Show', @merchant_child
\|
= link_to 'Back', merchant_children_path

app/views/merchant_children/index.html.haml
%h1 Listing merchant_children

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @merchant_children.each do |merchant_child|
    %tr
      %td= merchant_child.name
      %td= link_to 'Show', merchant_child
      %td= link_to 'Edit', edit_merchant_child_path(merchant_child)
      %td= link_to 'Destroy', merchant_child, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Merchant child', new_merchant_child_path

app/views/merchant_children/new.html.haml
%h1 New merchant_child

= render 'form'

= link_to 'Back', merchant_children_path

app/views/merchant_children/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @merchant_child.name

= link_to 'Edit', edit_merchant_child_path(@merchant_child)
\|
= link_to 'Back', merchant_children_path