config/routes.rb
Bg::Application.routes.draw do

  resources :merchant_children

  resources :merchant_pers

  resources :templates
  root to: "templates#index"
  resources :income
  resources :expence

  get 'public/data/:id' => 'templates#download', as: :download

end

app/views/templates/_form.html.haml
.row.panel
  %h3 Grundeinstellungen
  = form_for @template do |f|
    - if @template.errors.any?
      #error_explanation
        %h2= "#{pluralize(@template.errors.count, "error")} prohibited this template from being saved:"
        %ul
          - @template.errors.full_messages.each do |msg|
            %li= msg
    .large-2.columns
      = f.label :bank
      = f.text_field :bank
    .large-2.columns
      = f.label :account_name
      = f.text_field :account_name
    .large-2.columns
      = f.label :start_amount
      = f.text_field :start_amount
    .large-2.columns
      = f.label :from_date
      = f.text_field :from_date, placeholder: '24/08/2014'
    .large-2.columns
      = f.label :to_date
      = f.text_field :to_date, placeholder: '26/08/2014'
    .large-2.columns
      = f.submit 'Save', class: 'button small'


.row
  .large-12.columns
    #header
    #content


= javascript_tag do
  App.initialize();

app/views/templates/download.html.haml
= link_to 'Download your file', @file_url

app/views/templates/edit.html.haml
.row
  .large-12.columns
    %h1 Editing template

= render 'form'

#gethis
  %select#list_item.height_auto{:name => "list_item", :size => "4"}
    - MerchantPer.all.each_with_index do |hotel, index|
      - if index == 1
        %option{selected: "true"}
          = hotel.name
      - else
        %option
          = hotel.name

= link_to 'Show', @template
\|
= link_to 'Back', templates_path

app/views/templates/index.html.haml
%h1 Listing templates

%table
  %tr
    %th Bank
    %th Account name
    %th Start amount
    %th From date
    %th To date
    %th
    %th
    %th

  - @templates.each do |template|
    %tr
      %td= template.bank
      %td= template.account_name
      %td= template.start_amount
      %td= template.from_date
      %td= template.to_date
      %td= link_to 'Show', template
      %td= link_to 'Edit', edit_template_path(template)
      %td= link_to 'Destroy', template, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Template', new_template_path

app/views/templates/new.html.haml
%h1 New template

= render 'form'

= link_to 'Back', templates_path

app/views/templates/show.html.haml
%p#notice= notice

%p
  %b Bank:
  = @template.bank
%p
  %b Account name:
  = @template.account_name
%p
  %b Start amount:
  = @template.start_amount
%p
  %b From date:
  = @template.from_date
%p
  %b To date:
  = @template.to_date


= @list.each do |l|
  = l.name_arb + ' ' + l.ein
  %br

= link_to 'Edit', edit_template_path(@template)
\|
= link_to 'Back', templates_path
\|
= link_to 'Download your file', download_path + '.sta'

= @file_url