config/routes.rb
Bg::Application.routes.draw do

  resources :merchant_children

  resources :merchant_pers

  resources :templates
  root to: "templates#index"
  resources :income
  resources :expence

  get 'public/data/:id' => 'templates#download', as: :download

end

app/models/merchant_per.rb
class MerchantPer
  include Mongoid::Document
  field :name, type: String
  field :merchant_child_id, type: String

  has_many :merchant_children, class_name: 'MerchantChild', inverse_of: :merchant_per
end

app/controllers/merchant_pers_controller.rb
class MerchantPersController < ApplicationController
  before_action :set_merchant_per, only: [:show, :edit, :update, :destroy]

  # GET /merchant_pers
  # GET /merchant_pers.json
  def index
    @merchant_pers = MerchantPer.all
  end

  # GET /merchant_pers/1
  # GET /merchant_pers/1.json
  def show
  end

  # GET /merchant_pers/new
  def new
    @merchant_per = MerchantPer.new
  end

  # GET /merchant_pers/1/edit
  def edit
    @merchant_per = MerchantPer.new
  end

  # POST /merchant_pers
  # POST /merchant_pers.json
  def create
    @merchant_per = MerchantPer.new(merchant_per_params)

    respond_to do |format|
      if @merchant_per.save
        format.html { redirect_to @merchant_per, notice: 'Merchant per was successfully created.' }
        format.json { render action: 'show', status: :created, location: @merchant_per }
      else
        format.html { render action: 'new' }
        format.json { render json: @merchant_per.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchant_pers/1
  # PATCH/PUT /merchant_pers/1.json
  def update
    respond_to do |format|
      if @merchant_per.update(merchant_per_params)
        format.html { redirect_to @merchant_per, notice: 'Merchant per was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @merchant_per.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchant_pers/1
  # DELETE /merchant_pers/1.json
  def destroy
    @merchant_per.destroy
    respond_to do |format|
      format.html { redirect_to merchant_pers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant_per
      @merchant_per = MerchantPer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merchant_per_params
      params.require(:merchant_per).permit(:name)
    end
end

app/helpers/merchant_pers_helper.rb
module MerchantPersHelper
end

app/views/merchant_pers/_form.html.haml
= form_for @merchant_per do |f|
  - if @merchant_per.errors.any?
    #error_explanation
      %h2= "#{pluralize(@merchant_per.errors.count, "error")} prohibited this merchant_per from being saved:"
      %ul
        - @merchant_per.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/merchant_pers/edit.html.haml
%h1 Editing merchant_per

= render 'form'

= link_to 'Show', @merchant_per
\|
= link_to 'Back', merchant_pers_path

app/views/merchant_pers/index.html.haml
%h1 Listing merchant_pers
= Rails.env
%table
  %tr
    %th Name
    %th
    %th
    %th

  - @merchant_pers.each do |merchant_per|
    %tr
      %td= merchant_per.name
      %td= link_to 'Show', merchant_per
      %td= link_to 'Edit', edit_merchant_per_path(merchant_per)
      %td= link_to 'Destroy', merchant_per, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Merchant per', new_merchant_per_path

app/views/merchant_pers/new.html.haml
%h1 New merchant_per

= render 'form'

= link_to 'Back', merchant_pers_path

app/views/merchant_pers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @merchant_per.name

= link_to 'Edit', edit_merchant_per_path(@merchant_per)
\|
= link_to 'Back', merchant_pers_path